# Use the official Node.js 14 image as a base
FROM node:18.19.1-alpine AS development

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose port 4200 for the Angular development server
EXPOSE 4200 49153

# Command to run the Angular development server
CMD ["npm", "start"]
