version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: password$123
      MYSQL_DATABASE: bankingapp
      MYSQL_USER: bankingapp
      MYSQL_PASSWORD: password$user1
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      timeout: 5s
      retries: 55
    ports:
      - "3308:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    restart: always
    networks:
      - my-network
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=bankingapp
      - MYSQL_USER=bankingapp
      - MYSQL_PASSWORD=password$user1
      - SHOW_SQL=true
      - PEER_ENDPOINT:host.docker.internal:7051
    volumes:
      - ./backend/src:/app/src
      - ./fabric/network/organizations/peerOrganizations/org1.example.com:/app/fabric/org1.example.com
    depends_on:
      mysql:
        condition: service_healthy

networks:
  my-network:
    driver: bridge
