# Use the official Maven image as a base
FROM maven:3.8.4-openjdk-17-slim AS development

# Set the working directory in the container
WORKDIR /app

# Copy the Maven project file to the container
COPY pom.xml .

# Download dependencies
RUN mvn dependency:go-offline -B

# Copy the rest of the application code to the container
COPY src ./src

# Expose port 8080 for Spring Boot server
EXPOSE 8080

# Command to run the Spring Boot application
CMD ["mvn", "spring-boot:run"]
